name: chromatic 👓
on: push

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: '12.16.0'
            - name: Cache Dependencies
              uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: node-
            - run: |
                  yarn && yarn build
            - uses: chromaui/action@v1
              with:
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
                  token: ${{ secrets.GITHUB_TOKEN }}
